
[font]
size = 12.0

[font.normal]
family= "DroidSansM Nerd Font"
style = "Regular"

[window]
opacity = 0.8
padding = { x = 15, y = 15}

[general]
import = [
   "~/.config/alacritty/colors-alacritty.toml"
]



